ciphers/ciphers/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ciphersite.urls')),
    path('admin/', admin.site.urls),
]

ciphers/ciphersite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vigenere/', views.vigenere, name='vigenere'),
    path('des/', views.des, name='des'),
    path('rsa/', views.rsa, name='rsa'),
    path('md5/', views.md5, name='md5'),
    path('ci/', views.ci, name='ci'),
]

ciphers/ciphersite/models.py
from django.db import models

# Create your models here.

ciphers/ciphersite/forms.py
from django import forms
from .cipher_classes.vigenere import VigenereCipher
from .cipher_classes.rsa import RSACipher
from .cipher_classes.des import DESCipher
from .cipher_classes.md5 import MD5
from . import constants
import re


class VigenereForm(forms.Form):
    cipher = VigenereCipher()
    key = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    decrypted_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                  'rows': '5'}))
    encrypted_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                  'rows': '5'}))

    def clean(self):
        cleaned_data = super(VigenereForm, self).clean()
        if 'encrypt' in self.data:
            valid_chars_in_fields(self, ['key', 'decrypted_text'])
            fields_required(self, ['key', 'decrypted_text'], "This field is required when encrypting.")
        elif 'decrypt' in self.data:
            valid_chars_in_fields(self, ['key', 'encrypted_text'])
            fields_required(self, ['key', 'encrypted_text'], "This field is required when decrypting.")
        else:
            self.add_error('', "Missing submit type")
        return cleaned_data


class DESForm(forms.Form):
    cipher = DESCipher()
    key = forms.CharField(required=False, label="Key (8 Characters: 0-9,a-z,A-Z, and ascii symbols)",
                          min_length=8, max_length=8,
                          widget=forms.TextInput(attrs={'class': 'form-control'}))
    CHOICES = [('text', 'Text Input'),
               ('file', 'File Input')]
    input_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-check-input'}))
    decrypted_text = forms.CharField(required=False, label="Plain Text", widget=forms.Textarea(attrs={'rows': '5',
                                                                              'class': 'form-control'}))
    decrypted_file = forms.FileField(required=False, label="File (500k max)", widget=forms.ClearableFileInput(
                                                                                    attrs={'class': 'form-control'}))
    encrypted_text = forms.CharField(required=False, label="Cipher Hexadecimal", widget=forms.Textarea(attrs={'rows': '5',
                                                                              'class': 'form-control'}))
    encrypted_file = forms.FileField(required=False, label="Encrypted File (500k max)", widget=forms.ClearableFileInput(
                                                                                    attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super(DESForm, self).clean()
        input_type = cleaned_data.get('input_type', 'text')

        if 'encrypt' in self.data:
            fields_required(self, ['key', f'decrypted_{input_type}'], "This field is required when encrypting.")
        elif 'decrypt' in self.data:
            fields_required(self, ['key', f'encrypted_{input_type}'], "This field is required when decrypting.")
        elif 'generate_key' in self.data:
            pass
        else:
            pass
        if 'generate_key' not in self.data:
            valid_chars_in_fields(self, ['key'], characters=' -~')
        return cleaned_data


class RSAForm(forms.Form):
    cipher = RSACipher()
    public_key = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    private_key = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    decrypted_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                  'rows': '5'}))
    encrypted_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
                                                                                  'rows': '5'}))

    def clean(self):
        cleaned_data = super(RSAForm, self).clean()
        if 'encrypt' in self.data:
            fields_required(self, ['public_key', 'decrypted_text'], "This field is required when encrypting.")
        elif 'decrypt' in self.data:
            fields_required(self, ['private_key', 'encrypted_text'], "This field is required when decrypting.")
            valid_chars_in_fields(self, ['encrypted_text'], characters='0-9,')
        elif 'generate_keys' in self.data:
            pass
        else:
            self.add_error('', "Missing submit type")
        valid_chars_in_fields(self,
                              ['public_key', 'private_key'],
                              message="This field contains invalid characters. Only 0-9 and , are allowed.",
                              characters='0-9,')
        return cleaned_data


class MD5Form(forms.Form):
    cipher = MD5()
    CHOICES = [('text', 'Text Input'),
               ('file', 'File Input')]
    input_type = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-check-input'}))
    input_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': '4',
                                                                              'class': 'form-control'}))
    input_file = forms.FileField(required=False, label="Input file (10mb max)",
                                 widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    output_hash = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': '2',
                                                                               'class': 'form-control',
                                                                               'readonly': 'readonly'}))

    def clean(self):
        cleaned_data = super(MD5Form, self).clean()
        if self.data.get('hash'):
            input_type = cleaned_data.get('input_type', 'text')
            fields_required(self, [f'input_{input_type}'], "This field is required when hashing.")
            if input_type == 'text':
                pass
            elif input_type == 'file':
                pass
            else:
                self.add_error('', "At least one input field must be filled out.")
        return cleaned_data


def fields_required(form, fields, message="This field is required."):
    for field in fields:
        if not form.cleaned_data.get(field, ''):
            msg = forms.ValidationError(message)
            form.add_error(field, msg)
            form.fields[field].widget.attrs['class'] += ' is-invalid'


def valid_chars_in_fields(form, fields, message="This field contains invalid characters.", characters=' -~\t\r\n'):
    pattern = re.compile('^[' + characters + ']+$')
    for field in fields:
        contents = form.cleaned_data.get(field, '')
        if contents:
            if not re.search(pattern, contents):
                msg = forms.ValidationError(message)
                form.add_error(field, msg)
                form.fields[field].widget.attrs['class'] += ' is-invalid'

ciphers/ciphersite/views.py
import hashlib
import hmac
import json
import subprocess
import random
import string
from ciphers import settings
from decouple import config
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from .forms import VigenereForm, DESForm, MD5Form, RSAForm


def index(request):
    context = {}
    return render(request, 'ciphersite/index.html', context)


##
# Vigenere encryption/decryption page
def vigenere(request):
    if request.method == 'POST':
        vals = request.POST
        form = VigenereForm(vals)
        if form.is_valid():
            if 'encrypt' in vals:
                ciphertext = form.cipher.encrypt(form.cleaned_data['key'], form.cleaned_data['decrypted_text'])
                form.cleaned_data['encrypted_text'] = ciphertext
            elif 'decrypt' in vals:
                ciphertext = form.cipher.decrypt(form.cleaned_data['key'], form.cleaned_data['encrypted_text'])
                form.cleaned_data['decrypted_text'] = ciphertext
    else:
        form = VigenereForm()
    context = {'form': form}
    return render(request, 'ciphersite/vigenere.html', context)


##
# DES encryption/decryption page
def des(request):
    if request.method == 'POST':
        vals = request.POST
        form = DESForm(request.POST, request.FILES)
        if form.is_valid():
            if 'generate_key' in vals:
                form.cleaned_data['key'] = x = ''.join(random.choice(string.ascii_letters +
                                                                     string.punctuation +
                                                                     string.digits) for _ in range(8))
            elif 'encrypt' in vals:
                if form.cleaned_data.get('input_type') == 'file':
                    file = request.FILES.get('decrypted_file')
                    filename = file.name + '.enc'
                    output = form.cipher.encrypt(file.read(), form.cleaned_data['key'].encode()).hex()
                    response = HttpResponse(output, content_type="application/octet-stream")
                    response['Content-Disposition'] = 'inline; filename=' + filename
                    return response
                else:
                    ciphertext = form.cipher.encrypt(form.cleaned_data['decrypted_text'].encode(),
                                                     form.cleaned_data['key'].encode())
                    form.cleaned_data['encrypted_text'] = ciphertext.hex()
            elif 'decrypt' in vals:
                if form.cleaned_data.get('input_type') == 'file':
                    file = request.FILES.get('encrypted_file')
                    filename = file.name
                    filename = filename[::-1].replace('cne.', '', 1)[::-1]
                    fs = file.read().decode()
                    output = form.cipher.decrypt(bytearray.fromhex(fs), form.cleaned_data['key'].encode())
                    response = HttpResponse(bytes(output), content_type="application/octet-stream")
                    response['Content-Disposition'] = 'inline; filename=' + filename
                    return response
                else:
                    try:
                        input_arr = bytearray.fromhex(form.cleaned_data['encrypted_text'])
                        ciphertext = form.cipher.decrypt(input_arr, form.cleaned_data['key'].encode())
                        form.cleaned_data['decrypted_text'] = ciphertext.decode()
                    except BaseException:
                        form.add_error('', 'There was an error decrypting this text. ' + \
                                           'Please ensure the values you have entered are valid')
                        pass
            else:
                return HttpResponse('Invalid Request', status=400)
    else:
        form = DESForm({'input_type': 'text'})

    context = {'form': form}
    return render(request, 'ciphersite/des.html', context)


##
# RSA encryption/decryption page
def rsa(request):
    if request.method == 'POST':
        vals = request.POST
        form = RSAForm(vals)
        if form.is_valid():
            if 'generate_keys' in vals:
                private_key, public_key = form.cipher.generate_keys()
                form.cleaned_data['private_key'] = f"{private_key[0]},{private_key[1]}"
                form.cleaned_data['public_key'] = f"{public_key[0]},{public_key[1]}"
            elif 'encrypt' in vals:
                key_parts = [int(x.strip()) for x in form.cleaned_data['public_key'].split(',')]
                ciphertext = form.cipher.encrypt(form.cleaned_data['decrypted_text'], key_parts)
                form.cleaned_data['encrypted_text'] = ciphertext
            elif 'decrypt' in vals:
                key_parts = [int(x.strip()) for x in form.cleaned_data['private_key'].split(',')]
                ciphertext = form.cipher.decrypt(form.cleaned_data['encrypted_text'], key_parts)
                form.cleaned_data['decrypted_text'] = ciphertext
    else:
        form = RSAForm()
    context = {'form': form}
    return render(request, 'ciphersite/rsa.html', context)


##
# MD5 hash page
def md5(request):
    if request.method == 'POST':
        form = MD5Form(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data.get('input_text'):
                ciphertext = form.cipher.hex_hash(form.cleaned_data.get('input_text').encode())
                form.cleaned_data['output_hash'] = ciphertext
            elif form.cleaned_data.get('input_file'):
                ciphertext = form.cipher.hex_hash(request.FILES.get('input_file').read())
                form.cleaned_data['output_hash'] = ciphertext
            else:
                return HttpResponse('Invalid Request', status=400)
    else:
        form = MD5Form({'input_type': 'text'})

    context = {'form': form}
    return render(request, 'ciphersite/md5.html', context)


##
# Handle the continuous deployment endpoint
@csrf_exempt
def ci(request):
    headers = request.headers
    if any(header not in headers.keys() for header in ['X-Hub-Signature', 'X-Github-Event']):
        return HttpResponse('Invalid Request', status=400)

    secret = config('WEBHOOK_SECRET')
    git_signature = headers.get('X-Hub-Signature').replace("sha1=", "")
    signature = hmac.new(secret.encode(), request.body, hashlib.sha1)
    expected_signature = signature.hexdigest()
    if not hmac.compare_digest(git_signature, expected_signature):
        return HttpResponseForbidden('Invalid signature header')

    event_type = headers["X-Github-Event"]
    obj = json.loads(request.body)
    if event_type == 'push':
        valid_branches_for_push = ['master']
        ref = obj.get('ref')
        if any(branch in ref for branch in valid_branches_for_push):
            commits = obj.get('commits')
            if commits:
                num_commits = str(len(commits))
                subprocess.Popen([f"{str(settings.BASE_DIR)}/post-receive.sh", num_commits, ref])
                return HttpResponse(f"Successfully landed {num_commits} commits on {ref}")
            else:
                return HttpResponse(f"No commits to land on {ref}")
        else:
            return HttpResponse(f"This server does not support landing commits from {ref}")

    return HttpResponse("Request was validated, but this event is not handled by the server")

ciphers/ciphersite/templates/ciphersite/base.html
{% load static %}
{% load ciphersite_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Security Ciphers Project{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'ciphersite/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ciphersite/site.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Ciphers</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% block nav_content %}
                    <a class="nav-link" href="{% url 'vigenere' %}">VIGENERE</a>
                    <a class="nav-link" href="{% url 'des' %}">DES</a>
                    <a class="nav-link" href="{% url 'rsa' %}">RSA</a>
                    <a class="nav-link" href="{% url 'md5' %}">MD5</a>
                    {% endblock %}
                </div>
            </div>
        </div>
    </nav>

    <div class="mt-lg-3 p-5 container-lg shadow-lg h-100">
        {% block content %}
            <p>Add content here</p>
        {% endblock %}
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% block script_section %}{% endblock %}
</html>

ciphers/ciphersite/templates/ciphersite/des.html
{% extends 'ciphersite/encryption_form.html' %}

{% block title %}DES Cipher{% endblock title %}

{% block form_tag_params %}
    enctype="multipart/form-data"
{% endblock form_tag_params %}

{% block insert_block_after_field %}
    {% if field.name == 'key' %}
        <div class="mb-3">
            <button type="submit" name="generate_key" value="generate_key" class="btn btn-sm btn-primary btn-block">Generate Key</button>
        </div>
    {% endif %}
{% endblock insert_block_after_field %}

{% block script_section %}
<script>
    $(document).ready(function() {
        if ($('input[type=radio][name=input_type]:checked').val() === 'file') {
            $("#id_decrypted_text_container").hide();
            $("#id_encrypted_text_container").hide();
        } else {
            $("#id_decrypted_file_container").hide();
            $("#id_encrypted_file_container").hide();
        }

        $('input[type=radio][name=input_type]').change(function() {
            if ($(this).val() === 'file') {
                $("#id_decrypted_file_container").show();
                $("#id_encrypted_file_container").show();
                $("#id_decrypted_text_container").hide();
                $("#id_encrypted_text_container").hide();
            } else {
                $("#id_decrypted_file_container").hide();
                $("#id_encrypted_file_container").hide();
                $("#id_decrypted_text_container").show();
                $("#id_encrypted_text_container").show();
            }
        });
    });
</script>
{% endblock script_section %}

ciphers/ciphersite/templates/ciphersite/encryption_form.html
{% extends 'ciphersite/base.html' %}

{% block content %}
{% block form_tag %}
<form action="{% block action %}{% endblock %}" method="post" {% block form_tag_params %}{% endblock %}>
{% endblock form_tag %}
    {% csrf_token %}
    {% block fields_loop %}
        {% block non_field_error_section %}
            <div class="mb-3">
            {% for error in form.non_field_errors %}
                <label class="text-danger">{{ error }}</label><br>
            {% endfor %}
            </div>
        {% endblock non_field_error_section %}

        {% block before_fields %}{% endblock before_fields %}

        {% for field in form %}
            {% with widget=field.field.widget %}
            {% block field_row %}
                <div id="{{ field.auto_id }}_container" class="mb-3">
                    {% block field_row_contents %}
                        {% if field.widget_type == 'radioselect' %}
                            {% for choice in field.field.choices %}
                                <div class="form-check">
                                    <input type="radio"
                                           class="form-check-input"
                                           name="{{ field.name }}"
                                           id="{{ field.auto_id }}_{{ choice.0 }}"
                                           value="{{ choice.0 }}"
                                           {% if field.data == choice.0 %}checked{% endif %}/>
                                    <label for="{{ field.auto_id }}_{{ choice.0 }}" class="form-check-label">{{ choice.1 }}</label>
                                </div>
                            {% endfor %}
                        {% else %}
                            {% block label_display %}
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {% endblock label_display %}

                            {% if field.widget_type == 'textarea' %}
                                <textarea id="{{ field.id_for_label }}"
                                      name="{{ field.name }}"
                                      {% for attr, value in widget.attrs.items %}
                                          {{ attr }}="{{ value }}"
                                      {% endfor %}>{{ field.form|get_field_data:field.name }}</textarea>
                            {% elif field.widget_type == 'text' %}
                                <input type="text"
                                       name="{{ field.name }}"
                                       {% for attr, value in widget.attrs.items %}
                                            {{ attr }}="{{ value }}"
                                       {% endfor %}
                                        value="{{ field.form|get_field_data:field.name }}">
                            {% else %}
                                {% block field_display %}
                                    {{ field }}
                                {% endblock field_display %}
                            {% endif %}
                        {% endif %}

                        {% block error_display %}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {{ field.errors|break_join|safe }}
                                </div>
                            {% endif %}
                        {% endblock error_display %}

                    {% endblock field_row_contents %}
                </div>
            {% endblock field_row %}
            {% endwith %}

            {% block insert_block_after_field %}{% endblock insert_block_after_field %}
        {% endfor %}
    {% endblock fields_loop %}

    {% block after_fields %}{% endblock after_fields %}

    <div class="mb-3">
        {% block submit_section %}
            <div class="row">
                {% block submit_row %}
                    <div class="d-grid col-6">
                        <button type="submit" name="encrypt" value="encrypt" class="btn btn-primary btn-block">Encrypt</button>
                    </div>
                    <div class="d-grid col-6">
                        <button type="submit" name="decrypt" value="decrypt" class="btn btn-secondary btn-block">Decrypt</button>
                    </div>
                {% endblock submit_row %}
            </div>
        {% endblock submit_section %}
    </div>
</form>
{% endblock content %}

ciphers/ciphersite/templates/ciphersite/index.html
{% extends "ciphersite/base.html" %}

{% block content %}
    <a href="{% url 'vigenere' %}">Vigenere Cipher</a><br>
    <a href="{% url 'des' %}">DES Encryption</a><br>
    <a href="{% url 'rsa' %}">RSA Encryption</a><br>
    <a href="{% url 'md5' %}">MD5 Hash</a>
{% endblock content %}

ciphers/ciphersite/templates/ciphersite/md5.html
{% extends 'ciphersite/encryption_form.html' %}

{% block title %}MD5 Cipher{% endblock title %}

{% block form_tag_params %}
    enctype="multipart/form-data"
{% endblock form_tag_params %}

{% block submit_row %}
    <div class="d-grid">
        <button type="submit" id="hash_button" name="hash" value="hash" class="btn btn-primary btn-block">Hash</button>
    </div>
{% endblock submit_row %}

{% block script_section %}
<script>
    $(document).ready(function() {
        if ($('input[type=radio][name=input_type]:checked').val() === 'file') {
            $("#id_input_text_container").hide();
        } else {
            $("#id_input_file_container").hide();
        }

        $('input[type=radio][name=input_type]').change(function() {
            if ($(this).val() === 'file') {
                $("#id_input_file_container").show();
                $("#id_input_text_container").hide();
            } else {
                $("#id_input_file_container").hide();
                $("#id_input_text_container").show();
            }
        });

        $("#hash_button").click(function() {
            $("#id_output_hash").html("");
            $(this).html("Hashing...");
        });
    });
</script>
{% endblock script_section %}

ciphers/ciphersite/templates/ciphersite/rsa.html
{% extends 'ciphersite/encryption_form.html' %}

{% block title %}RSA Cipher{% endblock title %}

{% block insert_block_after_field %}
    {% if field.name == 'private_key' %}
        <div class="mb-3">
            <button type="submit" name="generate_keys" value="generate_keys" class="btn btn-sm btn-primary btn-block">Generate New Keys</button>
        </div>
    {% endif %}
{% endblock insert_block_after_field %}

ciphers/ciphersite/templates/ciphersite/vigenere.html
{% extends 'ciphersite/encryption_form.html' %}

{% block title %}Vigenere Cipher{% endblock title %}